# secret defines
apiVersion: v1
kind: Secret
metadata:
  name: psql-postgres-secret
type: Opaque
data:
  PSQL_DATABASE: a29uZw== 
  PSQL_USER: a29uZw==
  PSQL_PASSWORD: bXlrb25ncGFzc3dvcmQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:latest
        env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: psql-postgres-secret
                  key: PSQL_DATABASE

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: psql-postgres-secret
                  key: PSQL_USER
                  
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: psql-postgres-secret
                  key: PSQL_PASSWORD
          
        ports:
        - containerPort: 5432
